name: 'Hello Perl'
description: 'Simplest Perl composite action'
branding:
  icon: 'briefcase'
  color: 'blue'
inputs:
  action-input:
    description: 'What it is about'
    required: false # or not
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: |
        use JSON::PP;
        my $jsoner = JSON::PP->new->ascii->pretty->allow_nonref;
        print  $jsoner->encode( %ENV );
      shell: perl {0}
