name: 'Hello Perl'
description: 'Simplest Perl composite action'
branding:
  icon: 'briefcase'
  color: 'blue'
inputs:
  action-input:
    description: 'What it is about'
    required: false # or not
    default: 'World'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - run: print %ENV;
      shell: perl {0}
    - name: Print input
      env:
        TEMPLATE_INPUT: ${{ inputs.action-input}}
      run: print $ENV{'ACTION_INPUT'}
      shell: perl {0}
