name: Run basic action
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run basic action
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run basic test
      uses: ./
